export const FIND_ALL = "FIND_ALL";
export const FIND_ALL_SUCCESS = "FIND_ALL_SUCCESS";
export const FIND_ALL_FAILURE = "FIND_ALL_FAILURE";

export const FIND_ALL_DATA = "FIND_ALL_DATA";
export const FIND_ALL_DATA_SUCCESS = "FIND_ALL_DATA_SUCCESS";
export const FIND_ALL_DATA_FAILURE = "FIND_ALL_DATA_FAILURE";

export const GET_ALL_ACTIVE = "GET_ALL_ACTIVE";
export const GET_ALL_ACTIVE_SUCCESS = "GET_ALL_ACTIVE_SUCCESS";
export const GET_ALL_ACTIVE_FAILURE = "GET_ALL_ACTIVE_FAILURE";



export const GET_CASE_ACTIVE_BY_DATE_1 = "GET_CASE_ACTIVE_BY_DATE_1";
export const GET_CASE_ACTIVE_BY_DATE_1_SUCCESS = "GET_CASE_ACTIVE_BY_DATE_1_SUCCESS";
export const GET_CASE_ACTIVE_BY_DATE_1_FAILURE = "GET_CASE_ACTIVE_BY_DATE_1_FAILURE";


export const GET_CASE_ACTIVE_BY_DATE_2 = "GET_CASE_ACTIVE_BY_DATE_2";
export const GET_CASE_ACTIVE_BY_DATE_2_SUCCESS = "GET_CASE_ACTIVE_BY_DATE_2_SUCCESS";
export const GET_CASE_ACTIVE_BY_DATE_2_FAILURE = "GET_CASE_ACTIVE_BY_DATE_2_FAILURE";






